### ISSUE TITLE
Please release some versionof this library too

### ISSUE THREAD

**Issue by ArsenShnurkov** [mrward/xdt#4]
It is possible to get sources through git submodules mechanism, but it will not be a specific version.
Please create a tag (tarball release) of this library too. Thanks.

Might be it will be enough to exclude tests from build of monodevelop ?

    /var/calculate/tmp/portage/dev-util/monodevelop-5.7.0-r1/work/monodevelop-5.7/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.csproj (default targets) ->
    /usr/lib64/mono/4.5/Microsoft.Common.targets (ResolveAssemblyReferences target) ->
    
	/usr/lib64/mono/4.5/Microsoft.Common.targets:  warning : Reference 'Microsoft.Web.XmlTransform' not resolved

I didn't found it's usage in other places:

    # LANG=C grep -R "Microsoft.Web.XmlTransform" * | grep -v "Binary file"
    monodevelop-5.7/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/XmlDocumentTransformTests.cs:using Microsoft.Web.XmlTransform;
    monodevelop-5.7/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.csproj:    <Reference Include="Microsoft.Web.XmlTransform">
    monodevelop-5.7/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.csproj:      <HintPath>..\..\..\..\external\nuget-binary\Microsoft.Web.XmlTransform.dll</HintPath>
    monodevelop-5.7/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.addin.xml:		<Import assembly="Microsoft.Web.XmlTransform.dll" />

UPD: I created a patch for Main.sln which excludes MonoDevelop.PackageManagement.Tests.csproj from build in all configurations, 
https://github.com/gentoo/dotnet/pull/36/files
and successfully finished my build of monodevelop.

But tag will be necessary if one will decide to build tests.

UPD2: Nuget itself depends on Xdt:
Project "./src/Core/Core.csproj" 
FileModifiers/XdtTransformer.cs(5,17): error CS0234: The type or namespace name `Web' does not exist in the namespace `Microsoft'. Are you missing an assembly reference?

**Comment by mrward** [comment]
I have added two tags:

  * Release-NuGet-2.8.1-Mono
  * Release-NuGet-2.8.3-Mono
